import { Quote } from './types';

export const FALLBACK_QUOTES: Quote[] = [
    { id: '1', quote: "I'm going to make him an offer he can't refuse.", movie: "The Godfather", type: 'movie' },
    { id: '2', quote: "May the Force be with you.", movie: "Star Wars", type: 'movie' },
    { id: '3', quote: "You talkin' to me?", movie: "Taxi Driver", type: 'movie' },
    { id: '4', quote: "There's no place like home.", movie: "The Wizard of Oz", type: 'movie' },
    { id: '5', quote: "Here's looking at you, kid.", movie: "Casablanca", type: 'movie' },
    { id: '6', quote: "My precious.", movie: "The Lord of the Rings: The Two Towers", type: 'movie' },
    { id: '7', quote: "I'll be back.", movie: "The Terminator", type: 'movie' },
    { id: '8', quote: "You're gonna need a bigger boat.", movie: "Jaws", type: 'movie' },
    { id: '9', quote: "E.T. phone home.", movie: "E.T. the Extra-Terrestrial", type: 'movie' },
    { id: '10', quote: "To be, or not to be.", movie: "Hamlet", type: 'movie' },
    { id: '11', quote: "Frankly, my dear, I don't give a damn.", movie: "Gone with the Wind", type: 'movie' },
    { id: '12', quote: "Show me the money!", movie: "Jerry Maguire", type: 'movie' },
    { id: '13', quote: "Why so serious?", movie: "The Dark Knight", type: 'movie' },
    { id: '14', quote: "Life is like a box of chocolates.", movie: "Forrest Gump", type: 'movie' },
    { id: '15', quote: "I am your father.", movie: "Star Wars: The Empire Strikes Back", type: 'movie' },
    { id: '16', quote: "Keep your friends close, but your enemies closer.", movie: "The Godfather Part II", type: 'movie' },
    { id: '17', quote: "You can't handle the truth!", movie: "A Few Good Men", type: 'movie' },
    { id: '18', quote: "I'll have what she's having.", movie: "When Harry Met Sally", type: 'movie' },
    { id: '19', quote: "Bond. James Bond.", movie: "Dr. No", type: 'movie' },
    { id: '20', quote: "Hasta la vista, baby.", movie: "Terminator 2: Judgment Day", type: 'movie' },
    { id: '21', quote: "After all, tomorrow is another day!", movie: "Gone with the Wind", type: 'movie' },
    { id: '22', quote: "Elementary, my dear Watson.", movie: "The Adventures of Sherlock Holmes", type: 'movie' },
    { id: '23', quote: "Houston, we have a problem.", movie: "Apollo 13", type: 'movie' },
    { id: '24', quote: "You had me at 'hello'.", movie: "Jerry Maguire", type: 'movie' },
    { id: '25', quote: "Just keep swimming.", movie: "Finding Nemo", type: 'movie' },
    { id: '26', quote: "Winter is coming.", movie: "Game of Thrones", type: 'show' },
    { id: '27', quote: "I'm the king of the world!", movie: "Titanic", type: 'movie' },
    { id: '28', quote: "The first rule of Fight Club is: You do not talk about Fight Club.", movie: "Fight Club", type: 'movie' },
    { id: '29', quote: "To infinity and beyond!", movie: "Toy Story", type: 'movie' },
    { id: '30', quote: "Carpe diem. Seize the day, boys.", movie: "Dead Poets Society", type: 'movie' }
];
